server:
 port: 9000
spring:
 application:
   name: StockService
eureka:
 client:
  register-with-eureka: true
  fetch-registry: true
  service-url:
   defaultZone: http://localhost:9003/eureka/
instance:
 hostname: localhost